apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: launchable-image-build
on:
  push:
    branches:
      - "**"
  workflow_dispatch: {}
jobs:
  build_backend_jenkins:
    steps:
      - uses: cloudbees-io/cbci-run-job@v2
        name: trigger_cbci
        kind: build
        with:
          url: https://core.cloudbees.guru/shared-demos
          username: ${{vars.GURUCI_USERNAME}}
          token: ${{secrets.GURUCI_TOKEN}}
          job-name: spring-petclinic/job/spring-petclinic-angular-backend/
          parameters: '{"version":"${{ cloudbees.version }}"}'
  build:
    steps:
      - uses: docker://alpine/git:latest
        run: |
          git config --global --add safe.directory /cloudbees/workspace
      - name: checkout
        uses: cloudbees-io/checkout@v1
      - uses: cloudbees-io/configure-oci-credentials@v1
        name: Setup Docker Hub Registry
        with:
          registry: index.docker.io
          username: ${{ vars.GURUREP_DOCKER_USERNAME }}
          password: ${{ secrets.GURUREP_DOCKER_PASSWORD }}
      - name: Build a container image with Kaniko!
        uses: cloudbees-io/kaniko@v1
        with:
          dockerfile: Dockerfile
          context: .
          destination: gururepservice/launchable:latest
          build-args: BUILDKIT_CONTEXT_KEEP_GIT_DIR=1,BUILDKIT_INLINE_CACHE=1
          labels: maintainer=Jakub Zarzycki,version=latest
